stages:
    - checks
    - test
    - deploy

pre-commit:
    stage: checks
    image: python:3.12-bookworm
    variables:
        PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
    cache:
        paths:
            - ${PRE_COMMIT_HOME}
    script:
        - pip install pre-commit
        - pre-commit run --all-files

.tox_setup:
    before_script:
        - pip install tox

pylint:
    stage: checks
    extends: .tox_setup
    image: python:3.12-bookworm
    script:
        - tox -e pylint

test-docs:
    extends: .tox_setup
    image: python:3.12-bookworm
    script:
        - tox -e docs

test:
  extends: .tox_setup
  image: python:3.$PYTHON_VERSION-bookworm
  parallel:
    matrix:
    - PYTHON_VERSION: [10, 11, 12, 13]
  script:
    - tox -e py3$PYTHON_VERSION
    - bash <(curl -s https://codecov.io/bash)

deploy-pypi:
    stage: deploy
    image: python:3.12-bookworm
    before_script:
        - pip install -U pip twine wheel build
    script:
        - python -m build
        - twine upload dist/*
    only:
        - tags
