from typing import Iterable, Tuple

import grpc

from .discord_api_pb2 import (
    Channel,
    Embed,
    GetGuildChannelsRequest,
    Message,
    SendChannelMessageRequest,
    SendDirectMessageRequest,
)
from .discord_api_pb2_grpc import DiscordApiStub
from .helpers import parse_error_details


class DiscordProxyException(Exception):
    """An exception generated by Discord Proxy."""


class DiscordProxyGrpcError(DiscordProxyException):
    """Error related to the gRPC protocol.

    These are usually caused by network issues between the client
    and the Discord Proxy server.
    """

    def __init__(self, status: grpc.StatusCode, details: str) -> None:
        super().__init__(details)
        self._status = status.value
        self._details = details

    @property
    def details(self) -> str:
        """Details about the error state."""
        return self._details

    @property
    def status(self) -> Tuple[int, str]:
        """GRPC status code."""
        return self._status


class DiscordProxyHttpError(DiscordProxyException):
    """Error related to the Discord API.

    These are usually caused by API errors on the Discord server.
    """

    def __init__(self, status: int, code: int, text: str) -> None:
        super().__init__(text)
        self._status = status
        self._code = code
        self._text = text

    @property
    def code(self) -> str:
        """JSON error code."""
        return self._code

    @property
    def status(self) -> int:
        """HTTP status code."""
        return self._status

    @property
    def text(self) -> str:
        """Error message."""
        return self._text


class DiscordClient:
    """Client for interacting with Discord.

    All methods raise either ``DiscordProxyHttpError`` or ``DiscordProxyGrpcError``.
    """

    def __init__(self, target: str = None, options=None) -> None:
        """
        Args:
            target: The server address. Default is: "localhost:50051"
            options: An optional list of key-value pairs to configure the channel.
        """
        self.target = str(target) if target else "localhost:50051"
        self.options = options

    def get_guild_channels(self, guild_id: int) -> Iterable[Channel]:
        """Get all channels.

        Args:
            guild_id: ID of guild to get the channel for

        Returns:
            Guild channels
        """
        with grpc.insecure_channel(self.target, self.options) as channel:
            client = DiscordApiStub(channel)
            request = GetGuildChannelsRequest(guild_id=guild_id)
            try:
                response = client.GetGuildChannels(request)
            except Exception as ex:
                raise self._to_discord_proxy_exception(ex)
        return response.channels

    def create_channel_message(
        self, channel_id: int, content: str = "", embed: Embed = None
    ) -> Message:
        """Create new message in a channel.

        Args:
            channel_id: ID of channel to create message in
            content: Text of the message
            embed: Embed of the message

        Returns:
            Created message
        """
        if not content and not embed:
            raise ValueError("Either content or embed need to be specified.")
        with grpc.insecure_channel(self.target, self.options) as grpc_channel:
            client = DiscordApiStub(grpc_channel)
            request = SendChannelMessageRequest(
                content=content, channel_id=channel_id, embed=embed
            )
            try:
                response = client.SendChannelMessage(request)
            except Exception as ex:
                raise self._to_discord_proxy_exception(ex)
        return response.message

    def create_direct_message(
        self, user_id: int, content: str = "", embed: Embed = None
    ) -> Message:
        """Create new direct message.

        Args:
            user_id: ID of user to create direct message for
            content: Text of the message
            embed: Embed of the message

        Returns:
            Created message
        """
        if not content and not embed:
            raise ValueError("Either content or embed need to be specified.")
        with grpc.insecure_channel(self.target, self.options) as grpc_channel:
            client = DiscordApiStub(grpc_channel)
            request = SendDirectMessageRequest(
                content=content, user_id=user_id, embed=embed
            )
            try:
                response = client.SendDirectMessage(request)
            except Exception as ex:
                raise self._to_discord_proxy_exception(ex)
        return response.message

    @staticmethod
    def _to_discord_proxy_exception(ex: Exception) -> DiscordProxyException:
        if not hasattr(ex, "details"):
            return ex
        details = parse_error_details(ex)
        if details.type == "HTTPException":
            return DiscordProxyHttpError(
                status=details.status, code=details.code, text=details.text
            )
        return DiscordProxyGrpcError(status=ex.code(), details=ex.details())
